#ifndef GUARD_CONFIG_PARTY_MENU_OVERRIDE_H
#define GUARD_CONFIG_PARTY_MENU_OVERRIDE_H

#ifdef OVR_RKSE_PARTY_MENU_DESIGN
#undef RKSE_PARTY_MENU_DESIGN
#define RKSE_PARTY_MENU_DESIGN             OVR_RKSE_PARTY_MENU_DESIGN
#endif

#endif // GUARD_CONFIG_PARTY_MENU_OVERRIDE_H
